server:
  port: 2003

spring:
  application:
    name: cloud-one-seata-account
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: account-service-group

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

logging:
  level:
    io:
      seata: info

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


feign:
  hystrix:
    enabled: false

