server:
  port: 9001

spring:
  application:
    name: cloud-one-nacos-provider
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

