server:
  port: 8888

spring:
  application:
    name: cloud-one-config
  cloud:
    #配置中心
    config:
      server:
        git:
          uri: https://github.com/poxiao123456/cloud-one-config.git
          force-pull: true
          search-paths:
            - config2
      # 读取标签
      label: master
  #        native:
#          search-locations: classpath:/config1/
# 新增消息队列并且暴露，不需要进行消息跟踪
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



#注册中心
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'