server:
  port: 8801

spring:
  application:
    name: cloud-one-stream-rabbitmq-provider
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      binders: #自此处配置要绑定的rabbitmq的服务信息
          defaultRabbit: #表示定义的名称，用于binding整合
            type: rabbit #消息组件类型
            envirenment: # 设置rabbitmq的相关的环境配置
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
      bindings: #服务的整合处理
        output: #这个名字是一个通道的名称
          destination: springboot-mq #表示要使用的exchange名称定义
          content-type: application/json #设置消息类型，本次为json
          binder: defaultRabbit #设置要绑定的消息服务的具体设置

#cloud-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true


