server:
  port: 80

spring:
  application:
    name: cloud-one-consumer-user
  main:
    allow-bean-definition-overriding: true

#cloud-client
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/cloud/



username:
  name: zhangsan


# YML文件里需要开启日志的Feign客户端
logging:
  level:
    com.poxiao.cloud.feign: debug

#openFeign配置
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ConnectionTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  # 同一台实例的最大重试次数，但是不包括首次调用，默认为1次
  MaxAutoRetries: 1
  # 重试负载均衡其他实例的最大重试次数，不包括首次调用，默认为0次
  MaxAutoRetriesNextServer: 0
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        #Feign的连接建立超时时间，默认为10秒
        connectTimeout: 10000
        #Feign的请求处理超时时间，默认为60
        readTimeout: 60000
        #Feign使用默认的超时配置，在该类源码中可见，默认单次请求最大时长1秒，重试5次
        retryer: feign.Retryer.Default
hystrix:
  command:
    default:
      execution:
        timeout:
          #为false则超时控制有ribbon控制，为true则hystrix超时和ribbon超时都是用，但是谁小谁生效，默认为true
          enable: true
        isolation:
          thread:
            #hystrix的超时时长默认1秒，最常修改的参数
            timeoutInMilliseconds: 8000
circuitBreaker:
  # 触发熔断的最小请求次数，默认为20
  requestVolumeThreshold: 20
  # 休眠时长，默认为5秒
  sleepWindowInMilliseconds: 5000
  # 触发熔断的失败请求最小占比，默认50%
  errorThresholdPercentage: 50